const types = {
    FETCHING_START: 'FETCHING_START',
    FETCHING_FINISHED: 'FETCHING_FINISHED',
    FETCHING_ERROR: 'FETCHING_ERROR',
    SEARCH_FINISHING: 'SEARCH_FINISHING',
    RESET_STATE: 'RESET_STATE',
}

export default types