const types = {
    IS_LOGIN: 'START_LUNCH',
    LOGIN_FINISHED: 'LOGIN_FINISHED',
    LOGIN_ERROR: 'LOGIN_ERROR',

    IS_REGISTER: 'START_REGISTER',
    REGISTER_FINISHED: 'REGISTER_FINISHED',
    REGISTER_ERROR: 'REGISTER_ERROR',

    IS_LOGOUT: 'IS_LOGOUT',
    LOGOUT_FINISHED: 'LOGOUT_FINISHED',
    LOGOUT_ERROR: 'LOGOUT_ERROR',

    CHECK_USER: 'CHECK_USER'
}

export default types